export const exerciseLibrary = {
  arms: [
    { name: "Bicep Curl", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 35, difficulty: 2,
      muscles: "Biceps, Forearms", tip: "Keep elbows pinned to your sides" },
    { name: "Tricep Dips", type: "Strength", sets: 3, reps: 10, rest: "60s", kcal: 30, difficulty: 2,
      muscles: "Triceps, Shoulders", tip: "Don't let shoulders shrug up" },
    { name: "Hammer Curl", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 32, difficulty: 1,
      muscles: "Biceps, Brachialis", tip: "Neutral grip, slow on the way down" },
    { name: "Overhead Tricep Extension", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 28, difficulty: 2,
      muscles: "Triceps", tip: "Keep core tight, don't arch back" },
    { name: "Push Up", type: "Strength", sets: 3, reps: 10, rest: "60s", kcal: 40, difficulty: 2,
      muscles: "Chest, Triceps, Core", tip: "Body in a straight line throughout" },
    { name: "Wrist Circles", type: "Mobility", sets: 2, reps: 15, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Wrists, Forearms", tip: "Slow and controlled both directions" },
    { name: "Arm Cross Stretch", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Shoulders, Upper Arms", tip: "Hold 30 seconds each side" },
    { name: "Wall Push Up", type: "Mobility", sets: 3, reps: 12, rest: "30s", kcal: 15, difficulty: 1,
      muscles: "Chest, Triceps", tip: "Great beginner option" },
    { name: "Plank to Downdog", type: "Mobility", sets: 3, reps: 8, rest: "45s", kcal: 22, difficulty: 2,
      muscles: "Arms, Shoulders, Core", tip: "Push floor away on downdog" },
    { name: "Resistance Band Pull Apart", type: "Strength", sets: 3, reps: 15, rest: "45s", kcal: 18, difficulty: 1,
      muscles: "Shoulders, Upper Back", tip: "Squeeze shoulder blades together" }
  ],
  legs: [
    { name: "Bodyweight Squat", type: "Strength", sets: 3, reps: 15, rest: "60s", kcal: 45, difficulty: 1,
      muscles: "Quads, Glutes, Hamstrings", tip: "Knees track over toes" },
    { name: "Reverse Lunge", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 42, difficulty: 2,
      muscles: "Quads, Glutes, Hamstrings", tip: "Step back far enough so front knee stays behind toes" },
    { name: "Sumo Squat", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 48, difficulty: 2,
      muscles: "Inner Thighs, Glutes, Quads", tip: "Toes pointed out at 45 degrees" },
    { name: "Wall Sit", type: "Strength", sets: 3, reps: 45, rest: "60s", kcal: 35, difficulty: 2,
      muscles: "Quads, Glutes", tip: "Thighs parallel to floor" },
    { name: "Step Up", type: "Strength", sets: 3, reps: 10, rest: "60s", kcal: 50, difficulty: 2,
      muscles: "Quads, Glutes, Calves", tip: "Drive through the heel on top" },
    { name: "Standing Quad Stretch", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Quadriceps", tip: "Hold ankle not foot, stand tall" },
    { name: "Hip Flexor Lunge Stretch", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Hip Flexors, Quads", tip: "Sink hips low, feel the stretch in front hip" },
    { name: "Leg Swing", type: "Mobility", sets: 2, reps: 15, rest: "30s", kcal: 8, difficulty: 1,
      muscles: "Hips, Hamstrings", tip: "Hold wall for balance, keep swing controlled" },
    { name: "Calf Raise", type: "Strength", sets: 3, reps: 20, rest: "45s", kcal: 20, difficulty: 1,
      muscles: "Calves", tip: "Full range — all the way up and down" },
    { name: "Hamstring Curl (floor)", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 30, difficulty: 2,
      muscles: "Hamstrings, Glutes", tip: "Squeeze glutes at the top" }
  ],
  back: [
    { name: "Superman Hold", type: "Strength", sets: 3, reps: 12, rest: "45s", kcal: 25, difficulty: 2,
      muscles: "Lower Back, Glutes", tip: "Lift chest and legs simultaneously" },
    { name: "Bent Over Row (water bottle)", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 35, difficulty: 2,
      muscles: "Upper Back, Lats, Biceps", tip: "Hinge at hips, flat back" },
    { name: "Cat Cow", type: "Mobility", sets: 3, reps: 10, rest: "30s", kcal: 8, difficulty: 1,
      muscles: "Spine, Lower Back", tip: "Breathe in on cow, out on cat" },
    { name: "Child's Pose", type: "Flexibility", sets: 2, reps: 45, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Lower Back, Lats, Hips", tip: "Walk hands forward for deeper stretch" },
    { name: "Reverse Snow Angel (floor)", type: "Strength", sets: 3, reps: 12, rest: "45s", kcal: 20, difficulty: 1,
      muscles: "Upper Back, Rear Delts", tip: "Keep arms straight, thumbs up" },
    { name: "Thread the Needle", type: "Mobility", sets: 2, reps: 10, rest: "30s", kcal: 6, difficulty: 1,
      muscles: "Thoracic Spine, Shoulders", tip: "Rotate slowly, feel the mid-back open" },
    { name: "Bird Dog", type: "Strength", sets: 3, reps: 10, rest: "45s", kcal: 22, difficulty: 2,
      muscles: "Lower Back, Core, Glutes", tip: "Don't let hips rotate" },
    { name: "Doorway Chest Opener", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Chest, Front Shoulders, Back", tip: "Lean gently forward through doorway" },
    { name: "Seated Forward Fold", type: "Flexibility", sets: 2, reps: 45, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Hamstrings, Lower Back", tip: "Flex feet, hinge from hips not waist" },
    { name: "Scapular Squeeze", type: "Mobility", sets: 3, reps: 15, rest: "30s", kcal: 10, difficulty: 1,
      muscles: "Upper Back, Rhomboids", tip: "Imagine squeezing a pencil between shoulder blades" }
  ],
  chest: [
    { name: "Push Up", type: "Strength", sets: 3, reps: 10, rest: "60s", kcal: 40, difficulty: 2,
      muscles: "Chest, Triceps, Core", tip: "Body straight as a plank" },
    { name: "Incline Push Up", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 30, difficulty: 1,
      muscles: "Upper Chest, Triceps", tip: "Hands on elevated surface like a table" },
    { name: "Wide Push Up", type: "Strength", sets: 3, reps: 10, rest: "60s", kcal: 38, difficulty: 2,
      muscles: "Outer Chest, Shoulders", tip: "Wider than shoulder width hands" },
    { name: "Chest Squeeze (prayer press)", type: "Strength", sets: 3, reps: 15, rest: "45s", kcal: 15, difficulty: 1,
      muscles: "Inner Chest", tip: "Press palms together hard at chest height" },
    { name: "Floor Chest Fly (light weights)", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 28, difficulty: 2,
      muscles: "Chest, Front Shoulders", tip: "Slight bend in elbows throughout" },
    { name: "Doorway Pec Stretch", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Chest, Front Shoulders", tip: "Hold at gentle tension, don't strain" },
    { name: "Chest Opener (arms wide)", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Chest, Biceps" },
    { name: "Shoulder Rotation", type: "Mobility", sets: 2, reps: 15, rest: "30s", kcal: 6, difficulty: 1,
      muscles: "Shoulder Joint, Chest", tip: "Full slow circles both directions" },
    { name: "Sphinx Pose", type: "Mobility", sets: 2, reps: 30, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Chest, Abs, Spine", tip: "Elbows under shoulders, lift gently" },
    { name: "Decline Push Up", type: "Strength", sets: 3, reps: 8, rest: "60s", kcal: 42, difficulty: 3,
      muscles: "Lower Chest, Triceps", tip: "Feet elevated on chair or sofa" }
  ],
  core: [
    { name: "Dead Bug", type: "Strength", sets: 3, reps: 10, rest: "45s", kcal: 20, difficulty: 2,
      muscles: "Deep Core, Lower Back", tip: "Press lower back into floor throughout" },
    { name: "Plank Hold", type: "Strength", sets: 3, reps: 30, rest: "60s", kcal: 25, difficulty: 2,
      muscles: "Full Core, Shoulders", tip: "Don't let hips sag or pike up" },
    { name: "Bicycle Crunch", type: "Strength", sets: 3, reps: 16, rest: "60s", kcal: 30, difficulty: 2,
      muscles: "Obliques, Upper Abs", tip: "Rotate from ribs not elbows" },
    { name: "Leg Raise", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 28, difficulty: 3,
      muscles: "Lower Abs, Hip Flexors", tip: "Lower legs slow, don't let back arch" },
    { name: "Russian Twist", type: "Strength", sets: 3, reps: 20, rest: "60s", kcal: 25, difficulty: 2,
      muscles: "Obliques, Core", tip: "Lift feet for extra challenge" },
    { name: "Hollow Body Hold", type: "Strength", sets: 3, reps: 20, rest: "60s", kcal: 18, difficulty: 3,
      muscles: "Full Core", tip: "Lower back glued to floor" },
    { name: "Supine Twist", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Obliques, Spine, Hips", tip: "Keep shoulders flat on floor" },
    { name: "90-90 Hip Stretch", type: "Mobility", sets: 2, reps: 30, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Hips, Obliques", tip: "Both knees at 90 degree angle" },
    { name: "Bear Crawl", type: "Mobility", sets: 3, reps: 10, rest: "45s", kcal: 35, difficulty: 2,
      muscles: "Core, Shoulders, Hips", tip: "Knees hover 1 inch off floor" },
    { name: "Side Plank", type: "Strength", sets: 3, reps: 20, rest: "60s", kcal: 22, difficulty: 2,
      muscles: "Obliques, Glutes, Shoulders", tip: "Stack feet or stagger for balance" }
  ],
  glutes: [
    { name: "Glute Bridge", type: "Strength", sets: 3, reps: 15, rest: "60s", kcal: 30, difficulty: 1,
      muscles: "Glutes, Hamstrings, Core", tip: "Squeeze hard at the top for 1 second" },
    { name: "Single Leg Glute Bridge", type: "Strength", sets: 3, reps: 10, rest: "60s", kcal: 35, difficulty: 2,
      muscles: "Glutes, Hamstrings", tip: "Keep hips level throughout" },
    { name: "Donkey Kick", type: "Strength", sets: 3, reps: 15, rest: "45s", kcal: 28, difficulty: 1,
      muscles: "Glutes, Lower Back", tip: "Flex foot, drive heel to ceiling" },
    { name: "Fire Hydrant", type: "Strength", sets: 3, reps: 15, rest: "45s", kcal: 22, difficulty: 1,
      muscles: "Glutes, Hip Abductors", tip: "Keep core tight, don't tilt" },
    { name: "Curtsy Lunge", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 40, difficulty: 2,
      muscles: "Glutes, Inner Thighs, Quads", tip: "Step behind and across" },
    { name: "Sumo Deadlift", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 45, difficulty: 2,
      muscles: "Glutes, Inner Thighs, Hamstrings", tip: "Push floor away, don't pull up" },
    { name: "Pigeon Pose", type: "Flexibility", sets: 2, reps: 45, rest: "30s", kcal: 5, difficulty: 2,
      muscles: "Glutes, Hip Rotators", tip: "Square hips toward floor" },
    { name: "Figure 4 Stretch", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Glutes, Piriformis", tip: "Flex the foot of the crossed leg" },
    { name: "Hip Circle", type: "Mobility", sets: 2, reps: 10, rest: "30s", kcal: 8, difficulty: 1,
      muscles: "Hips, Glutes", tip: "Big slow circles, both directions" },
    { name: "Frog Pose", type: "Mobility", sets: 2, reps: 45, rest: "30s", kcal: 5, difficulty: 2,
      muscles: "Inner Thighs, Hips, Glutes", tip: "Rock gently forward and back" }
  ],
  fullbody: [
    { name: "Burpee", type: "Cardio", sets: 3, reps: 10, rest: "90s", kcal: 60, difficulty: 3,
      muscles: "Full Body", tip: "Step back instead of jump for low impact" },
    { name: "Mountain Climber", type: "Cardio", sets: 3, reps: 20, rest: "60s", kcal: 45, difficulty: 2,
      muscles: "Core, Shoulders, Legs", tip: "Keep hips level, fast feet" },
    { name: "Inchworm", type: "Mobility", sets: 3, reps: 8, rest: "45s", kcal: 22, difficulty: 2,
      muscles: "Hamstrings, Core, Shoulders", tip: "Walk hands out as far as possible" },
    { name: "Jump Squat", type: "Cardio", sets: 3, reps: 12, rest: "60s", kcal: 55, difficulty: 3,
      muscles: "Legs, Glutes, Core", tip: "Land softly with bent knees" },
    { name: "Lunge to Twist", type: "Mobility", sets: 3, reps: 10, rest: "45s", kcal: 30, difficulty: 2,
      muscles: "Legs, Core, Spine", tip: "Rotate toward front leg" },
    { name: "Slow Sun Salutation", type: "Flexibility", sets: 3, reps: 5, rest: "30s", kcal: 20, difficulty: 1,
      muscles: "Full Body", tip: "Hold each position for 3 breaths" },
    { name: "Bear Plank Shoulder Tap", type: "Strength", sets: 3, reps: 16, rest: "60s", kcal: 28, difficulty: 2,
      muscles: "Core, Shoulders, Arms", tip: "Minimal hip rotation" },
    { name: "Squat to Press", type: "Strength", sets: 3, reps: 12, rest: "60s", kcal: 48, difficulty: 2,
      muscles: "Legs, Shoulders, Core", tip: "Press overhead as you stand" },
    { name: "World's Greatest Stretch", type: "Mobility", sets: 2, reps: 6, rest: "30s", kcal: 10, difficulty: 2,
      muscles: "Hips, Spine, Hamstrings, Chest", tip: "Move slowly through each position" },
    { name: "Jumping Jack", type: "Cardio", sets: 3, reps: 30, rest: "45s", kcal: 35, difficulty: 1,
      muscles: "Full Body, Cardio", tip: "Low impact mod: step side to side" }
  ],
  mobility: [
    { name: "Slow Surya Namaskar", type: "Mobility", sets: 3, reps: 5, rest: "30s", kcal: 20, difficulty: 1,
      muscles: "Full Body", tip: "Hold each pose 3 breaths" },
    { name: "Child's Pose", type: "Flexibility", sets: 2, reps: 45, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Back, Hips, Shoulders", tip: "Arms extended or alongside body" },
    { name: "Hip 90-90", type: "Mobility", sets: 2, reps: 30, rest: "30s", kcal: 5, difficulty: 1,
      muscles: "Hip Rotators, Glutes", tip: "Sit tall, lean forward gently" },
    { name: "Thoracic Rotation", type: "Mobility", sets: 2, reps: 12, rest: "30s", kcal: 6, difficulty: 1,
      muscles: "Mid Back, Spine", tip: "Keep lower body still" },
    { name: "Ankle Circle", type: "Mobility", sets: 2, reps: 15, rest: "20s", kcal: 3, difficulty: 1,
      muscles: "Ankles, Calves", tip: "Both directions, slow and full range" },
    { name: "Neck Roll", type: "Mobility", sets: 2, reps: 8, rest: "20s", kcal: 2, difficulty: 1,
      muscles: "Neck, Upper Traps", tip: "Half circles only — don't roll back" },
    { name: "Seated Spinal Twist", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Spine, Obliques, Hips", tip: "Grow tall before you rotate" },
    { name: "Low Lunge (Anjaneyasana)", type: "Flexibility", sets: 2, reps: 30, rest: "30s", kcal: 6, difficulty: 1,
      muscles: "Hip Flexors, Quads, Groin", tip: "Sink hips low, arms reach up" },
    { name: "Downward Dog Hold", type: "Mobility", sets: 3, reps: 30, rest: "30s", kcal: 10, difficulty: 1,
      muscles: "Hamstrings, Calves, Shoulders, Back", tip: "Pedal feet to warm up calves" },
    { name: "Supine Figure 4", type: "Flexibility", sets: 2, reps: 45, rest: "30s", kcal: 4, difficulty: 1,
      muscles: "Glutes, Piriformis, Hips", tip: "Pull knee gently toward chest" }
  ]
};
